# Generated by Django 4.1.7 on 2023-03-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('no_persons', models.IntegerField()),
                ('has_instructor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('no_stars', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('price_per_night', models.FloatField()),
                ('room_number', models.IntegerField()),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Trip.accommodationtype')),
            ],
        ),
    ]
