# Generated by Django 4.1.7 on 2023-03-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0003_alter_accommodation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Trip.accommodationtype'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Trip.accommodation'),
        ),
    ]
