# Generated by Django 4.1.7 on 2023-03-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0006_alter_accommodation_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='room_number',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='check_in_time',
            field=models.TimeField(default='14:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='check_out_time',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='accommodation',
            field=models.ManyToManyField(blank=True, to='Trip.accommodation'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=models.ManyToManyField(blank=True, to='Trip.activity'),
        ),
    ]
