# Generated by Django 4.1.7 on 2023-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0007_remove_accommodation_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='check_in_time',
            field=models.TimeField(default='14:00:00'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='check_out_time',
            field=models.TimeField(default='10:00:00'),
        ),
    ]
