# Generated by Django 4.1.7 on 2023-03-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0008_alter_accommodation_check_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('speed', models.CharField(choices=[('SLOW', 'SLOW'), ('MEDIUM', 'MEDIUM'), ('FAST', 'FAST')], max_length=10)),
                ('comfort_level', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Trip.transportationtype')),
            ],
        ),
    ]
