# Generated by Django 4.1.7 on 2023-03-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0011_alter_accommodation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_ids', to='Trip.transportationtype'),
        ),
    ]
