# Generated by Django 4.1.7 on 2023-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0012_alter_transportation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='transportation',
        ),
        migrations.AddField(
            model_name='trip',
            name='transportation',
            field=models.ManyToManyField(blank=True, to='Trip.transportation'),
        ),
    ]
