# Generated by Django 4.1.7 on 2023-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0013_remove_trip_transportation_trip_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='accommodation',
            field=models.ManyToManyField(blank=True, related_name='accommodation', to='Trip.accommodation'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transportation',
            field=models.ManyToManyField(blank=True, related_name='transportation', to='Trip.transportation'),
        ),
    ]
