# Generated by Django 4.1.7 on 2023-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0014_alter_trip_accommodation_alter_trip_transportation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='transportation',
        ),
        migrations.AddField(
            model_name='trip',
            name='accommodations',
            field=models.ManyToManyField(blank=True, related_name='accommodations', to='Trip.accommodation'),
        ),
        migrations.AddField(
            model_name='trip',
            name='transportations',
            field=models.ManyToManyField(blank=True, related_name='transportations', to='Trip.transportation'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='activities', to='Trip.activity'),
        ),
    ]
