# Generated by Django 4.1.7 on 2023-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0015_remove_trip_accommodation_remove_trip_transportation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='name',
            field=models.CharField(default='unknown', max_length=60),
        ),
    ]
