# Generated by Django 4.1.7 on 2023-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0016_transportation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='no name', max_length=60),
        ),
    ]
