# Generated by Django 4.1.7 on 2023-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0017_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
