# Generated by Django 4.1.7 on 2023-03-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0018_alter_transportation_name_alter_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='check_in_time',
            field=models.TimeField(blank=True, default='14:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='check_out_time',
            field=models.TimeField(blank=True, default='10:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='no_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price_per_night',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='has_instructor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='no_persons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='comfort_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='speed',
            field=models.CharField(blank=True, choices=[('SLOW', 'SLOW'), ('MEDIUM', 'MEDIUM'), ('FAST', 'FAST')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
