# Generated by Django 4.1.7 on 2023-03-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0019_alter_accommodation_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accom_ids', to='Trip.accommodationtype', verbose_name='type'),
        ),
    ]
