# Generated by Django 4.1.7 on 2023-03-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0020_alter_accommodation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Trip.accommodationtype'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Trip.transportationtype'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='accommodations',
            field=models.ManyToManyField(blank=True, to='Trip.accommodation'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=models.ManyToManyField(blank=True, to='Trip.activity'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transportations',
            field=models.ManyToManyField(blank=True, to='Trip.transportation'),
        ),
    ]
