# Generated by Django 4.1.7 on 2023-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0027_trip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True),
        ),
    ]
