# Generated by Django 4.1.7 on 2023-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0029_alter_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
