INSERT INTO public."Trip_transportationtype"(id, name) VALUES
(1, 'Car'),
(2, 'Bus'),
(3, 'Train'),
(4, 'Flight'),
(5, 'Boat'),
(6, 'Cruise ship'),
(7, 'Bicycle'),
(8, 'Motorcycle'),
(9, 'Helicopter'),
(10, 'Hot air balloon'),
(11, 'Scooter'),
(12, 'Kayak'),
(13, 'Canoe'),
(14, 'Tram'),
(15, 'Subway'),
(16, 'Taxi'),
(17, 'Horseback riding'),
(18, 'Zip-line'),
(19, 'Paragliding'),
(20, 'Rafting');
