# Generated by Django 4.1.7 on 2023-03-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0004_alter_accommodation_type_alter_trip_accommodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='accommodation',
        ),
        migrations.AddField(
            model_name='trip',
            name='accommodation',
            field=models.ManyToManyField(to='Trip.accommodation'),
        ),
    ]
