# Generated by Django 4.1.7 on 2023-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0005_remove_trip_accommodation_trip_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='activities',
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='activities',
            field=models.ManyToManyField(to='Trip.activity'),
        ),
    ]
